module Constants
	JWT_EXPIRATION_HOURS_PROD = 7000
	JWT_EXPIRATION_HOURS_DEV = 10000000

	DEFAULT_TABLE_COUNT = 100
	DEFAULT_TABLE_PAGE = 1

	SIZE_PROPERTY_NAME = "size"

	# Constants for field lengths
	FIRST_NAME_MIN_LENGTH = 2
	FIRST_NAME_MAX_LENGTH = 20
	PASSWORD_MIN_LENGTH = 7
	PASSWORD_MAX_LENGTH = 25
	DEVICE_NAME_MIN_LENGTH = 2
	DEVICE_NAME_MAX_LENGTH = 30
	DEVICE_TYPE_MIN_LENGTH = 2
	DEVICE_TYPE_MAX_LENGTH = 30
	DEVICE_OS_MIN_LENGTH = 2
	DEVICE_OS_MAX_LENGTH = 30
	NAME_MIN_LENGTH = 2
	NAME_MAX_LENGTH = 20
	PROPERTY_NAME_MIN_LENGTH = 1
	PROPERTY_NAME_MAX_LENGTH = 100
	PROPERTY_VALUE_MIN_LENGTH = 1
	PROPERTY_VALUE_MAX_LENGTH = 65000

	# Constants for tests
	MATT_PASSWORD = "schachmatt"
end